name: End-to-End Tests

on: pull_request

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.14'

    - name: Install Chakra
      run: |
        pip install .

    - name: Install PARAM
      run: |
        git clone https://github.com/facebookresearch/param.git
        cd param/train/compute/python/
        git checkout c83ce8429110a86549c40fec5a01acbd9fbd54a4
        pip install .

    - name: Test chakra_trace_link Without Arguments
      run: |
        chakra_trace_link || [ $? -eq 2 ]

    - name: Test chakra_converter Without Arguments
      run: |
        chakra_converter || [ $? -eq 2 ]

    - name: Test chakra_visualizer Without Arguments
      run: |
        chakra_visualizer || [ $? -eq 2 ]

    - name: Test chakra_jsonizer Without Arguments
      run: |
        chakra_jsonizer || [ $? -eq 2 ]

    - name: Test chakra_timeline_visualizer Without Arguments
      run: |
        chakra_timeline_visualizer || [ $? -eq 2 ]
